In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


### Introduction to Tensors

Creating Tensors --> Number representation of Data in deep learning..

In [ ]:
# Scalars - Single element:
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
# Check Dimension of Tensor, turning Tensor into integer, shape of tensor
scalar.ndim, scalar.item(), scalar.shape

(0, 10, torch.Size([]))

In [ ]:
# Vector - single dimension tensor but can contain many numbers.
vector = torch.tensor([10, 10, 10, 10])
vector

tensor([10, 10, 10, 10])

In [ ]:
vector.ndim, vector.shape

(1, torch.Size([4]))

In [ ]:
# MATRIX - Tensors with 2 dimensions
MATRIX = torch.tensor([
    [10, 10, 5, 7],
    [9, 9, 10, 100]
])
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[ 10,  10,   5,   7],
         [  9,   9,  10, 100]]),
 2,
 torch.Size([2, 4]))

In [ ]:
# tensors - Tensors with more dimensions, tensors can represent almost anything.
TENSOR = torch.tensor([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,21,13],
    ]
])
TENSOR, TENSOR.ndim, TENSOR.shape, TENSOR.dtype

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 21, 13]]]),
 3,
 torch.Size([1, 3, 4]),
 torch.int64)

In [ ]:
#Random Tensors
# Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

rand_tensor = torch.rand(size=(2,4))
rand_tensor, rand_tensor.shape, rand_tensor.ndim, rand_tensor.dtype

(tensor([[0.7269, 0.9483, 0.4042, 0.7882],
         [0.5208, 0.9275, 0.6327, 0.5597]]),
 torch.Size([2, 4]),
 2,
 torch.float32)

In [ ]:
# The flexibility of torch.rand() is that we can adjust the size to be whatever we want.
#  EG: image shape of [224, 224, 3] ([height, width, color_channels]). (Also color channel comes first)


# Create a random tensor for img of size (224, 224, 3)
rand_tensor_img = torch.rand(size=(3, 224, 224))
rand_tensor_img.shape, rand_tensor.ndim, rand_tensor_img

(torch.Size([3, 224, 224]),
 2,
 tensor([[[0.4181, 0.1296, 0.9465,  ..., 0.8124, 0.7553, 0.4182],
          [0.5369, 0.8904, 0.1461,  ..., 0.0539, 0.7357, 0.6345],
          [0.2825, 0.6645, 0.4535,  ..., 0.6589, 0.7332, 0.1003],
          ...,
          [0.2654, 0.6168, 0.8085,  ..., 0.6390, 0.1245, 0.1312],
          [0.6854, 0.3788, 0.6756,  ..., 0.9613, 0.0683, 0.7830],
          [0.8271, 0.4809, 0.7089,  ..., 0.8523, 0.2096, 0.8166]],
 
         [[0.0122, 0.4580, 0.8222,  ..., 0.5274, 0.7653, 0.7973],
          [0.6933, 0.6642, 0.4589,  ..., 0.9177, 0.1096, 0.6316],
          [0.0382, 0.7760, 0.9565,  ..., 0.8751, 0.4291, 0.9947],
          ...,
          [0.1617, 0.9678, 0.0134,  ..., 0.2007, 0.8437, 0.8224],
          [0.5739, 0.6729, 0.6740,  ..., 0.6910, 0.4664, 0.1171],
          [0.7966, 0.0123, 0.5080,  ..., 0.2152, 0.4880, 0.6903]],
 
         [[0.6106, 0.9827, 0.8729,  ..., 0.2030, 0.2387, 0.9509],
          [0.9601, 0.9357, 0.5231,  ..., 0.5158, 0.5475, 0.0295],
        

Zeros and ones


In [ ]:
# Zeros and ones --> Tensors with numbers 0 and 1s
zeros_tensor = torch.zeros(size=(1, 3))
zeros_tensor, zeros_tensor.dtype

(tensor([[0., 0., 0.]]), torch.float32)

In [ ]:
ones_tensor = torch.ones(size=(1,3))
ones_tensor

tensor([[1., 1., 1.]])

Creating a range and tensors like

In [ ]:
# range might be deprecated, so consider arange
zero_to_one = torch.arange(start = 1, end = 11, step = 1)
zero_to_one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# like --> used to create a new tensor with same shape of another tensor...
like_tensor1 =  torch.rand_like(input = zero_to_one, dtype=torch.float)
like_tensor2 = torch.zeros_like(input = zero_to_one)
like_tensor1, like_tensor2

(tensor([0.4714, 0.4759, 0.8786, 0.6707, 0.5415, 0.1384, 0.4665, 0.3647, 0.4928,
         0.3285]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

## Tensor Data Types

```Note: ``` Tensor Datatypes is one of the 3 big errors we will run into Pytorch and deep learning...<br>
1. Tensors not the right Datatype<br>
2. Tensors not the right shape<br>
3. Tensors not the right device<br>

In [ ]:
# Default datatype for tensors is float32
# The higher the precision value (8, 16, 32), the more detail and hence data used to express a number

float_32_tensor = torch.rand([5,2], dtype=torch.float16)

# General Format of tensor
float_32_tensor  = torch.rand([5,2],
                              dtype=None, #Dtype for tensor
                              device=None, #What device is the tensor stored on? (usually GPU or CPU)
                              requires_grad=False # if True, operations performed on the tensor are recorded(tracked)
                              )
#To convert dtype, syntax: i.e: a.type(torch.float16)
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor, float_32_tensor.type(torch.float16)

(torch.float32,
 torch.Size([5, 2]),
 tensor([[0.6058, 0.2868],
         [0.4831, 0.3258],
         [0.4199, 0.7753],
         [0.6308, 0.3828],
         [0.0795, 0.8305]]),
 tensor([[0.6060, 0.2869],
         [0.4832, 0.3259],
         [0.4199, 0.7754],
         [0.6309, 0.3828],
         [0.0795, 0.8306]], dtype=torch.float16))

`Information from tensors`:

`shape` - what shape is the tensor? (some operations require specific shape rules)<br>
`dtype` - what datatype are the elements within the tensor stored in?<br>
`device` - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
tensor_info = torch.rand([2,4], dtype=torch.float16) #(same as torch.half)
tensor_info.dtype, tensor_info.shape, tensor_info.device #(Will Default to cpu)

(torch.float16, torch.Size([2, 4]), device(type='cpu'))

# Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

These operations are often a wonderful dance between:

Addition<br>
Substraction<br>
Multiplication (element-wise)<br>
Division<br>
Matrix multiplication<br>

In [ ]:
#Basic Operations:
tensor_add = torch.ones(size=[5], dtype=torch.int32) #(also alias as int32 = int)
tensor_add + 10

tensor_sub = torch.zeros_like(input=tensor_add)
tensor_sub - 10

tensor_mul = torch.rand_like(input=tensor_sub, dtype=torch.float32)
tensor_mul * 100 #Element Multiplication

tensor_div = tensor_add / 10
tensor_div

#Built-in functions for operations
tensor_func1 = torch.add(tensor_add , 10)
tensor_func1

tensor_func2 = torch.sub(tensor_func1, 1)
tensor_func2

tensor([10, 10, 10, 10, 10], dtype=torch.int32)

```Matrix multiplication```

---



PyTorch implements matrix multiplication functionality in the torch.matmul() or torch.mm() method.<br>

**The main two rules for matrix multiplication to remember are:**

**The inner dimensions must match:**<br>
(3, 2) @ (3, 2) won't work<br>
(2, 3) @ (3, 2) will work<br>
(3, 2) @ (2, 3) will work<br><hr>

**The resulting matrix has the shape of the outer dimensions:**<br>
(2, 3) @ (3, 2) -> (2, 2)<br>
(3, 2) @ (2, 3) -> (3, 3)

In [ ]:
tensor = torch.tensor([5,4,3])
tensor
torch.matmul(tensor, tensor) #Can also use the "@" symbol for matrix multiplication



tensor(50)

In [ ]:
%%time

# Matrix multi in hand
total = 0
for i in tensor:
  total += i.item() * i.item()
total

CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 2.47 ms


50

In [ ]:
%%time
torch.matmul(tensor, tensor) #Function is faster...

CPU times: user 1.41 ms, sys: 78 µs, total: 1.49 ms
Wall time: 1.81 ms


tensor(50)


One of the most common errors in deep learning (shape errors)

In [ ]:
tensor1 = torch.rand(5,4)
tensor2 = torch.rand(6,4)
torch.matmul(tensor1, tensor2) #Can be solved by Transpose...

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x4 and 6x4)

In [ ]:
print(f'Shape of T1 is (5, 4)\nShape of T2 is (6,4)\nShape of T2 tranpose is (4,6)')

In [ ]:
# Eg Of Transpose
# torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
# tensor.T - where tensor is the desired tensor to transpose

tensor2.T, tensor2.T.shape

# Tensor Aggregation

In [ ]:
#Finding the Min, Max, Mean, Sum of Tensor
# Either we can use Aggregator function torch.method(tensor) or method in tensor [i.e a.min()]

import torch
a = torch.arange(1,11)
b = torch.rand([5,2])
#Min
a.min(), torch.min(a)

#Max
a.max(), torch.max(a)

#Mean
mean_a = a.type(torch.float32).mean() #As mean involved float, we need to change data type as needed...
mean_a

#Sum
sum_a = a.sum() #sum all the value in tensors
sum_b = b.sum()
sum_b, sum_b.type(), mean_a

**Positional min/max**

You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [ ]:
torch.argmax(a), torch.argmin(a)

print(f"Index where max value occurs: {a.argmax()}")
print(f"Index where min value occurs: {a.argmin()}")

# Reshaping, viewing and stacking

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.




**Popular methods are:**

* Reshaping -  reshapes an input tensor to defined shape.
* View - Return a view of input tensor of certain shape, but keep the same memory(value) as the original tensor.
* Stacking - Combines multiple tensor each other on top (vstack) or side by side (hstack)
* Squeeze - Removes a all `1` dimension from a tensor.
* Unsqueeze - Add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.





In [ ]:
import torch

#Reshaping..
x = torch.tensor([10, 9, 8, 7, 5, 4, 5, 6,7,10])
print(x)
print(x.reshape(2,5))

# Also use as torch.reshape(input, dim)
x_reshaped = torch.reshape(x, (5,2))
print(x_reshaped.reshape(-1)) # -1 redefines shape as single dim...

#View
print('\nView')
v = x.view(5,2)
print(v) #View doesn't change shape of original tensor, they only do change values of original tensor...
print(x)

# If Value of v changes, then x(original) also changes..
v[:][0] = 1999 #(View of tensor shares the memory as original tensor...)
print(v)
print(x)

#Stacking
#Dim = 0 (vstack), dim = 1 (hstack)
s = torch.stack((x, x, x, x), dim=1)
print(s)

#Squeeze
print("\nSqueeze")
y = torch.rand(1,5,1)
print(y)
print(y.shape)
y_squeezed = y.squeeze()
print(y_squeezed.shape)
print(y_squeezed)

#Unsqueeze
print('\nunsqueeze')
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(y_unsqueezed)
print(y_unsqueezed.shape)

#Permute
# Eg: Swapping of color channel of view...
print('\npermute\n')
image_encode = torch.rand(224,224,3) #-> [height, width, color]
print(f'Before Permute: {image_encode.shape}')
permuted_img = image_encode.permute(dims=(2,0,1)) # [color, height, width]
print(f'After Permute: {permuted_img.shape}')





tensor([10,  9,  8,  7,  5,  4,  5,  6,  7, 10])
tensor([[10,  9,  8,  7,  5],
        [ 4,  5,  6,  7, 10]])
tensor([10,  9,  8,  7,  5,  4,  5,  6,  7, 10])

View
tensor([[10,  9],
        [ 8,  7],
        [ 5,  4],
        [ 5,  6],
        [ 7, 10]])
tensor([10,  9,  8,  7,  5,  4,  5,  6,  7, 10])
tensor([[1999, 1999],
        [   8,    7],
        [   5,    4],
        [   5,    6],
        [   7,   10]])
tensor([1999, 1999,    8,    7,    5,    4,    5,    6,    7,   10])
tensor([[1999, 1999, 1999, 1999],
        [1999, 1999, 1999, 1999],
        [   8,    8,    8,    8],
        [   7,    7,    7,    7],
        [   5,    5,    5,    5],
        [   4,    4,    4,    4],
        [   5,    5,    5,    5],
        [   6,    6,    6,    6],
        [   7,    7,    7,    7],
        [  10,   10,   10,   10]])

Squeeze
tensor([[[0.4253],
         [0.6988],
         [0.2795],
         [0.5995],
         [0.8625]]])
torch.Size([1, 5, 1])
torch.Size([5])
tensor([0.4253, 0.6988, 0.2795

# Tensor Indexing

In [ ]:
d = torch.rand(2,5, 5)
print(d)
# use ':' to select all dimension of target tensor..
d[:,0,:]

k = torch.arange(1,10).reshape(3,3)
print(k)
k[:,2]


tensor([[[0.2727, 0.1165, 0.2907, 0.8362, 0.5557],
         [0.6981, 0.0427, 0.8799, 0.3198, 0.2318],
         [0.3750, 0.4334, 0.5570, 0.5143, 0.1944],
         [0.9629, 0.9516, 0.9488, 0.2245, 0.9496],
         [0.0487, 0.5701, 0.8088, 0.0272, 0.7508]],

        [[0.4626, 0.8885, 0.2106, 0.6444, 0.6154],
         [0.4031, 0.2941, 0.7376, 0.9125, 0.5605],
         [0.6960, 0.0202, 0.1828, 0.0382, 0.1327],
         [0.6646, 0.2006, 0.1599, 0.9340, 0.7502],
         [0.7035, 0.7754, 0.4672, 0.4264, 0.0338]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


tensor([3, 6, 9])

#Pytorch and NumPy

NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

1. torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.<br>
2. torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [ ]:
#Numpy Array to tensor.
import torch
import numpy as np

array = np.arange(1.0,11.0) #np default type is float64
print(array, array.dtype, '\n')

#To convert np array into tensor.
nparray_to_tensor = torch.from_numpy(array)
print(nparray_to_tensor, '\n') # Final conversion is in form of original dtype

#Changing the value affect the another compatible tenspr and vice-versa...(shares same memory)
nparray_to_tensor[0] = 11
array + 1
print(array, nparray_to_tensor)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64 

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64) 

[11.  2.  3.  4.  5.  6.  7.  8.  9. 10.] tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)


In [ ]:
# Tensor to NumPy Array
tensor_py = torch.arange(1.0,10.0)
print(tensor, tensor.dtype, '\n') #tensor default type is float32

#To convert tensor to numpy array
tensor_to_array = tensor_py.numpy()
print(tensor_to_array, '\n') # Final conversion is in form of original dtype

#Changing the value also affect another...
tensor_to_array[0] = 10
print(tensor_to_array, tensor_py)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.float32 

[1. 2. 3. 4. 5. 6. 7. 8. 9.] 

[10.  2.  3.  4.  5.  6.  7.  8.  9.] tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])


#Reproducibility (trying to take the random out of random)

How neutral network learns?

* start with random numbers -> tensor operations -> try to make better (again and again and again)

To reduce the randomness in tensor, we need to use concepts of **Random seed**<br>
**Random seed** "flavour" the randomness

In [ ]:
import torch

#Create the 2 random tensor
rand_tensor_A = torch.rand(3,3)
rand_tensor_B = torch.rand(3,3)
print(rand_tensor_A, '\n', rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)



tensor([[0.4798, 0.7496, 0.2418],
        [0.0642, 0.8823, 0.5980],
        [0.8143, 0.7880, 0.7144]]) 
 tensor([[0.3939, 0.8319, 0.3079],
        [0.0439, 0.1751, 0.6132],
        [0.3634, 0.8089, 0.9987]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
# To solve the issue use resproducible tensor

#set the random seed.
RANDOM_SEED = 42 #(flavour)This sets a specific seed for PyTorch's random number generator

torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3,3) # function ensures that the sequence of random numbers is always the same every time you set this seed, making tensor generation predictable.

torch.manual_seed(RANDOM_SEED)
rand_tensor_D = torch.rand(3,3)

print(rand_tensor_C, '\n', rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


#Running tensors on GPUs (and making faster computations)

How to get?
* Google Colabs
* Use your own(Run everything locally on your own machine)
* Cloud computing (AWS, GCP, Azure)

In [1]:
#To check if you've got access to a Nvidia GPU, you can run !nvidia-smi.
#running pytorch and tensors on gpu, make computations faster..

# GPU = Thanks to CUDA + nividia(hardware) + Pytorch(working behind the scenes)
!nvidia-smi


Sat Sep  7 06:11:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [7]:
# Check GPU access with Pytorch
import torch
torch.cuda.is_available()

#setting up device agnostic code..
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device, '\n')

#Count the number of gpu
print(torch.cuda.device_count(), '\n')


cuda 

1 



In [21]:
# Putting the tensor and Models on GPU

tensor = torch.tensor([1,2,3,4,5], device='cuda')
print(tensor, '\n', tensor.device)

#moving tensor to gpu (if available)
tensor1 = torch.tensor([1,2,34,5,6])
tensor_on_gpu = tensor1.to(device) #by using to method we can move tensor on diff devices...
print(tensor_on_gpu)

tensor([1, 2, 3, 4, 5], device='cuda:0') 
 cuda:0
tensor([ 1,  2, 34,  5,  6], device='cuda:0')


In [19]:
#Moving back tensor on CPU

#Note: Numpy not work on GPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [24]:
# To fix issue we need to first set it to CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([ 1,  2, 34,  5,  6])

In [27]:
a = torch.rand(1,7)
b = torch.rand(1,7)

torch.matmul(a, b.T)

tensor([[1.9341]])